### PR TITLE
Update jsonPathTo.ts

### PR DESCRIPTION
**Pull request by Nuaduwodan**
I forgot to escape the hyphen, sorry about that. Also maybe the version in package.json should be increased as well.

### CODE REVIEW

**Comment by richie5um** [comment]
Thanks again. I'd made the changes to package.json but forgot to push :).

**Comment by Nuaduwodan** [comment]
It seems to me that the published version is one behind the source code. The now published version 1.4.3 seems to still have the bug and therefore doesn't show the path. could you please check if the published version has the hyphen escaped.

**Comment by richie5um** [comment]
Hmm. The code was definitely the latest. I've bumped the version, re-built/packaged, published. Hopefully this resolves whatever when wrong last publish.

**Comment by Nuaduwodan** [comment]
extension
As you can see in the screenshot the installed extension version 1.4.4 has the sources doubled. under out the changes are made but under out/src they are not. It seems that the sources under out/src are used. Maybe you could change your build process to put the files only under out/src.

**Comment by Nuaduwodan** [comment]
You can find the installed extension under %USERPROFILE%\.vscode\extensions\

**Pull request merged**
